services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    expose:
      - "3306"
    env_file: .env
    volumes:
      - mariadb_vlm:/var/lib/mysql/
    networks:
      - inception
    init: true
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    expose:
      - "9000"
    env_file: .env
    volumes:
      - wordpress_vlm:/var/www/wordpress/
    networks:
      - inception
    init: true
    restart: always
    depends_on:
      - mariadb

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - '443:443'
    env_file: .env  
    volumes:
      - wordpress_vlm:/var/www/wordpress/
    networks:
      - inception
    init: true
    restart: always
    depends_on:
      - wordpress

volumes:
  mariadb_vlm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/data/mariadb

  wordpress_vlm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/data/wordpress

networks:
  inception:
    driver: bridge
